using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Xunit;

namespace ProjectCeres.Analyzers.Tests;

/// <summary>
/// Tests for ResxParityGenerator (CER020). Uses CSharpSourceGeneratorTest directly
/// because the generator operates on AdditionalTexts, not syntax nodes.
/// </summary>
public class CER020_ResxParityGeneratorTests
{
    // The generator always emits a stub ResxParityCheck.g.cs regardless of input.
    // CSharpSourceGeneratorTest requires this to be declared in GeneratedSources.
    private const string GeneratedStubContent =
        "// <auto-generated>resx-parity-check executed by ProjectCeres.Analyzers.ResxParityGenerator</auto-generated>\n";

    private static CSharpSourceGeneratorTest<ResxParityGenerator, DefaultVerifier> CreateTest(
        params (string fileName, string content)[] additionalFiles)
    {
        var test = new CSharpSourceGeneratorTest<ResxParityGenerator, DefaultVerifier>
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net100,
            TestCode = "// placeholder",
        };
        foreach (var (fileName, content) in additionalFiles)
        {
            test.TestState.AdditionalFiles.Add((fileName, content));
        }
        // Declare the generated stub so the framework doesn't flag it as unexpected.
        test.TestState.GeneratedSources.Add((
            typeof(ResxParityGenerator),
            "ResxParityCheck.g.cs",
            GeneratedStubContent));
        return test;
    }

    // (a) EN + ES with identical keys → no diagnostic
    [Fact]
    public async Task NoFire_When_EN_ES_Have_Identical_Keys()
    {
        const string enContent = @"<?xml version=""1.0"" encoding=""utf-8""?>
<root>
  <data name=""Hello""><value>Hello</value></data>
  <data name=""Goodbye""><value>Goodbye</value></data>
</root>";
        const string esContent = @"<?xml version=""1.0"" encoding=""utf-8""?>
<root>
  <data name=""Hello""><value>Hola</value></data>
  <data name=""Goodbye""><value>Adios</value></data>
</root>";

        var test = CreateTest(
            ("Emails.en.resx", enContent),
            ("Emails.es.resx", esContent));

        await test.RunAsync();
    }

    // (b) EN missing a key ES has → diagnostic
    [Fact]
    public async Task Fires_When_EN_Missing_Key_ES_Has()
    {
        const string enContent = @"<?xml version=""1.0"" encoding=""utf-8""?>
<root>
  <data name=""Hello""><value>Hello</value></data>
</root>";
        const string esContent = @"<?xml version=""1.0"" encoding=""utf-8""?>
<root>
  <data name=""Hello""><value>Hola</value></data>
  <data name=""Goodbye""><value>Adios</value></data>
</root>";

        var test = CreateTest(
            ("Emails.en.resx", enContent),
            ("Emails.es.resx", esContent));

        test.ExpectedDiagnostics.Add(
            new DiagnosticResult(Diagnostics.CER020_ResxParityMissing)
                .WithArguments("Emails.en.resx", "Goodbye", "Emails.es.resx"));

        await test.RunAsync();
    }

    // (c) ES missing a key EN has → diagnostic
    [Fact]
    public async Task Fires_When_ES_Missing_Key_EN_Has()
    {
        const string enContent = @"<?xml version=""1.0"" encoding=""utf-8""?>
<root>
  <data name=""Hello""><value>Hello</value></data>
  <data name=""Goodbye""><value>Goodbye</value></data>
</root>";
        const string esContent = @"<?xml version=""1.0"" encoding=""utf-8""?>
<root>
  <data name=""Hello""><value>Hola</value></data>
</root>";

        var test = CreateTest(
            ("Emails.en.resx", enContent),
            ("Emails.es.resx", esContent));

        test.ExpectedDiagnostics.Add(
            new DiagnosticResult(Diagnostics.CER020_ResxParityMissing)
                .WithArguments("Emails.es.resx", "Goodbye", "Emails.en.resx"));

        await test.RunAsync();
    }

    // (d) Only EN file present → no diagnostic (parity only fires when ≥2 cultures present)
    [Fact]
    public async Task NoFire_When_Only_EN_Present()
    {
        const string enContent = @"<?xml version=""1.0"" encoding=""utf-8""?>
<root>
  <data name=""Hello""><value>Hello</value></data>
</root>";

        var test = CreateTest(("Emails.en.resx", enContent));

        await test.RunAsync();
    }
}
