using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Xunit;

namespace ProjectCeres.Analyzers.Tests;

// Uses CSharpSourceGeneratorTest directly (CER020 pattern) because the generator
// operates on AdditionalTexts (.resx), not syntax nodes.
public class EmailKeysGeneratorTests
{
    private static CSharpSourceGeneratorTest<EmailKeysGenerator, DefaultVerifier> NewTest(
        string testCode = "// placeholder")
        => new()
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net100,
            TestCode = testCode,
        };

    private const string Header =
        "// <auto-generated>email-key constants emitted by ProjectCeres.Analyzers.EmailKeysGenerator</auto-generated>\n";

    // 1. A resx with one template's 3 parts -> emits the nested class with 3 const members.
    [Fact]
    public async Task Emits_Nested_Class_With_Const_Members()
    {
        const string resx = @"<?xml version=""1.0"" encoding=""utf-8""?>
<root>
  <data name=""Foo.Subject""><value>S</value></data>
  <data name=""Foo.BodyText""><value>T</value></data>
  <data name=""Foo.BodyHtml""><value>H</value></data>
</root>";

        const string expected = Header +
@"namespace ProjectCeres.Common.Email
{
    internal static class EmailKeys
    {
        internal static class Foo
        {
            public const string BodyHtml = ""Foo.BodyHtml"";
            public const string BodyText = ""Foo.BodyText"";
            public const string Subject = ""Foo.Subject"";
        }
    }
}
";
        var test = NewTest();
        test.TestState.AdditionalFiles.Add(("EmailsResource.en.resx", resx));
        test.TestState.GeneratedSources.Add((typeof(EmailKeysGenerator), "EmailKeys.g.cs", expected));
        await test.RunAsync();
    }

    // 2. A resx missing a part -> that const is NOT emitted (deletion really removes the member).
    [Fact]
    public async Task Omits_Const_When_Resx_Key_Absent()
    {
        const string resx = @"<?xml version=""1.0"" encoding=""utf-8""?>
<root>
  <data name=""Foo.Subject""><value>S</value></data>
</root>";

        const string expected = Header +
@"namespace ProjectCeres.Common.Email
{
    internal static class EmailKeys
    {
        internal static class Foo
        {
            public const string Subject = ""Foo.Subject"";
        }
    }
}
";
        var test = NewTest();
        test.TestState.AdditionalFiles.Add(("EmailsResource.en.resx", resx));
        test.TestState.GeneratedSources.Add((typeof(EmailKeysGenerator), "EmailKeys.g.cs", expected));
        await test.RunAsync();
    }

    // 3. Malformed XML -> emits the header-only shell, does not throw.
    [Fact]
    public async Task Emits_Empty_Shell_On_Malformed_Xml()
    {
        const string resx = @"<root><data name=""Foo.Subject""><value>oops"; // unterminated

        const string expected = Header +
@"namespace ProjectCeres.Common.Email
{
    internal static class EmailKeys
    {
    }
}
";
        var test = NewTest();
        test.TestState.AdditionalFiles.Add(("EmailsResource.en.resx", resx));
        test.TestState.GeneratedSources.Add((typeof(EmailKeysGenerator), "EmailKeys.g.cs", expected));
        await test.RunAsync();
    }

    // 4. Hand-written code referencing a constant for a key NOT in the resx -> compile error.
    [Fact]
    public async Task Referencing_Absent_Key_Is_A_Compile_Error()
    {
        const string resx = @"<?xml version=""1.0"" encoding=""utf-8""?>
<root>
  <data name=""Foo.Subject""><value>S</value></data>
</root>";

        const string consumer = @"
namespace ProjectCeres.Common.Email
{
    internal static class Consumer
    {
        public static string Get() => EmailKeys.{|#0:Bar|}.Subject;
    }
}";
        const string expectedEmit = Header +
@"namespace ProjectCeres.Common.Email
{
    internal static class EmailKeys
    {
        internal static class Foo
        {
            public const string Subject = ""Foo.Subject"";
        }
    }
}
";
        var test = NewTest(consumer);
        test.TestState.AdditionalFiles.Add(("EmailsResource.en.resx", resx));
        test.TestState.GeneratedSources.Add((typeof(EmailKeysGenerator), "EmailKeys.g.cs", expectedEmit));
        // Referencing EmailKeys.Bar — a member the generator never emitted — is a compile error.
        // The compiler resolves it as a missing member (CS0117), not a missing nested type:
        // "'EmailKeys' does not contain a definition for 'Bar'". Args order is (containingType, member).
        test.ExpectedDiagnostics.Add(
            DiagnosticResult.CompilerError("CS0117").WithLocation(0).WithArguments("ProjectCeres.Common.Email.EmailKeys", "Bar"));
        await test.RunAsync();
    }
}
