using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace ProjectCeres.Analyzers;

[Generator(LanguageNames.CSharp)]
public sealed class EmailKeysGenerator : IIncrementalGenerator
{
    private const string EmailResxFileSuffix = "EmailsResource.en.resx";
    private const string GeneratedNamespace = "ProjectCeres.Common.Email";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var emailResx = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith(EmailResxFileSuffix, System.StringComparison.OrdinalIgnoreCase))
            .Collect();

        context.RegisterSourceOutput(emailResx, (spc, files) =>
        {
            // group keys by prefix: "PasswordResetRequest" -> { "Subject", "BodyText", "BodyHtml" }
            var byPrefix = new SortedDictionary<string, SortedSet<string>>(System.StringComparer.Ordinal);

            foreach (var file in files)
            {
                foreach (var key in ParseKeys(file))
                {
                    var dot = key.IndexOf('.');
                    if (dot <= 0 || dot >= key.Length - 1) continue; // no prefix.part split
                    var prefix = key.Substring(0, dot);
                    var part = key.Substring(dot + 1);
                    if (!SyntaxFacts.IsValidIdentifier(prefix) || !SyntaxFacts.IsValidIdentifier(part)) continue;
                    if (!byPrefix.TryGetValue(prefix, out var parts))
                    {
                        parts = new SortedSet<string>(System.StringComparer.Ordinal);
                        byPrefix[prefix] = parts;
                    }
                    parts.Add(part);
                }
            }

            spc.AddSource("EmailKeys.g.cs", Emit(byPrefix));
        });
    }

    private static string Emit(SortedDictionary<string, SortedSet<string>> byPrefix)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated>email-key constants emitted by ProjectCeres.Analyzers.EmailKeysGenerator</auto-generated>\n");
        sb.Append("namespace ").Append(GeneratedNamespace).Append("\n{\n");
        sb.Append("    internal static class EmailKeys\n    {\n");
        foreach (var prefix in byPrefix.Keys)
        {
            sb.Append("        internal static class ").Append(prefix).Append("\n        {\n");
            foreach (var part in byPrefix[prefix])
            {
                sb.Append("            public const string ").Append(part)
                  .Append(" = \"").Append(prefix).Append('.').Append(part).Append("\";\n");
            }
            sb.Append("        }\n");
        }
        sb.Append("    }\n}\n");
        return sb.ToString();
    }

    private static List<string> ParseKeys(AdditionalText file)
    {
        var keys = new List<string>();
        try
        {
            var content = file.GetText()?.ToString();
            if (content is null) return keys;
            var doc = XDocument.Parse(content);
            foreach (var data in doc.Descendants("data"))
            {
                var name = data.Attribute("name")?.Value;
                if (name is not null) keys.Add(name);
            }
        }
        catch
        {
            // Malformed XML — emit nothing (CER020 + the compiler surface real problems).
        }
        return keys;
    }
}
