using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;

namespace ProjectCeres.Analyzers;

[Generator(LanguageNames.CSharp)]
public sealed class ResxParityGenerator : IIncrementalGenerator
{
    private static readonly Regex ResxFileName = new(@"^(.+)\.(en|es)\.resx$", RegexOptions.Compiled | RegexOptions.IgnoreCase);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var resxFiles = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith(".resx", System.StringComparison.OrdinalIgnoreCase));

        var grouped = resxFiles.Collect();

        context.RegisterSourceOutput(grouped, (spc, files) =>
        {
            var bases = new Dictionary<string, Dictionary<string, AdditionalText>>();

            foreach (var file in files)
            {
                var name = System.IO.Path.GetFileName(file.Path);
                var match = ResxFileName.Match(name);
                if (!match.Success) continue;

                var baseName = match.Groups[1].Value;
                var culture = match.Groups[2].Value.ToLowerInvariant();

                if (!bases.TryGetValue(baseName, out var cultureMap))
                {
                    cultureMap = new Dictionary<string, AdditionalText>();
                    bases[baseName] = cultureMap;
                }
                cultureMap[culture] = file;
            }

            foreach (var kvp in bases)
            {
                var cultureMap = kvp.Value;
                if (cultureMap.Count < 2) continue;

                var keysByCulture = cultureMap.ToDictionary(
                    c => c.Key,
                    c => ParseKeys(c.Value));

                var allKeys = keysByCulture.SelectMany(k => k.Value).Distinct().ToList();

                foreach (var cultureEntry in cultureMap)
                {
                    var culture = cultureEntry.Key;
                    var file = cultureEntry.Value;
                    var missing = allKeys.Where(k => !keysByCulture[culture].Contains(k)).ToList();
                    foreach (var missingKey in missing)
                    {
                        var present = cultureMap.First(c => keysByCulture[c.Key].Contains(missingKey));
                        var diagnostic = Diagnostic.Create(
                            Diagnostics.CER020_ResxParityMissing,
                            Location.None,
                            System.IO.Path.GetFileName(file.Path),
                            missingKey,
                            System.IO.Path.GetFileName(present.Value.Path));
                        spc.ReportDiagnostic(diagnostic);
                    }
                }
            }

            spc.AddSource("ResxParityCheck.g.cs",
                "// <auto-generated>resx-parity-check executed by ProjectCeres.Analyzers.ResxParityGenerator</auto-generated>\n");
        });
    }

    private static HashSet<string> ParseKeys(AdditionalText file)
    {
        var keys = new HashSet<string>();
        try
        {
            var content = file.GetText()?.ToString();
            if (content is null) return keys;
            var doc = XDocument.Parse(content);
            foreach (var data in doc.Descendants("data"))
            {
                var name = data.Attribute("name")?.Value;
                if (name is not null) keys.Add(name);
            }
        }
        catch
        {
            // Malformed XML — silent for now; future CER021 can report this
        }
        return keys;
    }
}
